### PR TITLE
Fix #23: Update colors settings for tabs

### LINKED ISSUE #23: Hard to distinguish selected editor tab
Currently it is hard to distinguish the selected editor tab when many tabs are opened.

image

### Additional info

| Q                | A
| ---------------- | ---
| Plugin Version   | 1.9
| IDE and version  | 2020.1
| Operating system | Windows 10

### PR DESCRIPTION
**Pull request by gayanper**
Use new attributes to support new releases of intelliJ
Fixes : https://github.com/samdark/intellij-visual-studio-code-dark-plus/issues/23

### CODE REVIEW

**Comment by samdark** [comment]
Looks good when tab is active and editor is active:

image

Does not look as good when tab is active but I'm focused on file tree:

image

In VS code it always stays as in the first screenshot. Is it possible to make this element the same color as active tab?

image

**Comment by gayanper** [comment]
Did some update to make it more closer to vscode

**Comment by samdark** [comment]
Looks great now. Thanks!

image

**Comment by samdark** [comment]
Thank you!

**Pull request merged**
