### PR TITLE
Fix #55: change line color and height

### LINKED ISSUE #55: Tab color in new UI
### What the issue is?
The active tab color is not different from the color of the other tabs in the new UI that will be released in 2022.3

### Screenshots
image (Active tab is the second one)

### How would you fix it?

I would update the theme colors. If I have some spare time, I will create a PR for this Soon(TM)

### Additional info

| Q                | A
| ---------------- | ---
| Plugin Version   | 2.6
| IDE and version  | IntelliJ IDEA Community 2022.3 EAP
| Operating system | Ubuntu 22.04

### PR DESCRIPTION
**Pull request by Argon42**
image

| Q             | A
| ------------- | ---
| Is bugfix?    | ✔
| New feature?  | ❌
| Fixed issues  | https://github.com/samdark/intellij-visual-studio-code-dark-plus/issues/55

### CODE REVIEW

**Comment by samdark** [comment]
Need to adjust it a bit before merge.

**Comment by pasha-vuiko** [comment]
Hi, any updates here?

**Comment by samdark** [comment]
Sorry, I was extremely busy. I'll get back to the issue but if you can help adjusting it to be closer to VSCode (now it looks slightly different), that would be awesome.

**Comment by pasha-vuiko** [comment]
I have no experience with such things (editing of intellij themes), but I'll try my best

**Comment by samdark** [comment]
Thanks. I'll get to it one day. Need to free up some time...

**Comment by alexbaeza** [comment]
I'd like to +1 this PR, Hi @samdark Would it be possible to get this merged in?

Reasoning: while it is true that in vscode tabs do not have the "active tab indicator" (blue underline), this is a feature of the intellij new ui, and therefore we should style it to match the vscode colours rather than "hide it" to match the vscode tabs.

Personally, I love the new ui combined with this awesome theme. 🚀 

There will be quite a few things to add for the new ui but I think this one, in particular, is important as active tabs are important :)

**Comment by samdark** [comment]
Yes. Need some time to actually test it in action.

**Comment by alexbaeza** [comment]
> Yes. Need some time to actually test it in action.

Thank you very much, highly appreciate it. I am trying to find everything that changed and got added to see if I can put together a PR for the new UI but seems to be a difficult task :)

**Comment by samdark** [comment]
It is. Thank you very much.

**Comment by samdark** [comment]
@Argon42 thanks for the patch and sorry it took so long to actually release it.

**Comment by jsodeman** [comment]
Thank you both!

**Comment by DAmNRelentless** [comment]
Don't you think that's a bit... too much?


The text gets hard to read.

**Comment by samdark** [comment]
Hmm... it doesn't look like that for me:

image

**Comment by DAmNRelentless** [comment]
I'm using IntelliJ Ultimate with the new UI. 🤔

**Comment by jsodeman** [comment]
This is Rider and Webstorm latest with the New UI turned on.

image

image

**Comment by DAmNRelentless** [comment]
Yes, I restarted multiple times.
```
IntelliJ IDEA 2023.1.1 (Ultimate Edition)
Build #IU-231.8770.65, built on April 27, 2023
```

**Comment by Mom0aut** [comment]
I got the same issue with the new `IntelliJ Ultimate UI` enabled

**Pull request merged**
